import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { base64ToBytes } from "../src/shared/base64";
import { decrypt, deriveKey, encrypt, importAesKey, sha3_512Hex } from "../src/shared/crypto";

interface Fixtures {
  sha3_512: { input: string; hex: string }[];
  cases: {
    username: string;
    password: string;
    salt: string;
    rounds: number;
    keyHex: string;
    plaintext: string;
    payload: string;
  }[];
}

// Generated by tests/fixtures/generate_crypto_fixtures.py with the desktop client's CipherManager.
const fixtures = JSON.parse(
  readFileSync(new URL("./fixtures/crypto.json", import.meta.url), "utf8"),
) as Fixtures;

const hex = (bytes: Uint8Array) => Buffer.from(bytes).toString("hex");
const keyFromHex = (h: string) => importAesKey(new Uint8Array(Buffer.from(h, "hex")));

describe("sha3_512Hex", () => {
  it.each(fixtures.sha3_512)("matches Python for $input", ({ input, hex }) => {
    expect(sha3_512Hex(input)).toBe(hex);
  });
});

describe("deriveKey", () => {
  it.each(fixtures.cases)("matches Python PBKDF2 for $username/$rounds", async (c) => {
    expect(hex(await deriveKey(c.username, c.password, c.salt, c.rounds))).toBe(c.keyHex);
  });
});

describe("decrypt", () => {
  it.each(fixtures.cases)("opens a payload encrypted by the desktop client ($username)", async (c) => {
    expect(await decrypt(await keyFromHex(c.keyHex), c.payload)).toBe(c.plaintext);
  });

  it("rejects a tampered payload", async () => {
    const c = fixtures.cases[0];
    const envelope = JSON.parse(c.payload);
    const tag = base64ToBytes(envelope.tag);
    tag[0] ^= 1;
    envelope.tag = Buffer.from(tag).toString("base64");
    await expect(decrypt(await keyFromHex(c.keyHex), JSON.stringify(envelope))).rejects.toThrow();
  });

  it("rejects plaintext", async () => {
    await expect(decrypt(await keyFromHex(fixtures.cases[0].keyHex), "just text")).rejects.toThrow();
  });
});

describe("encrypt", () => {
  it("produces the desktop envelope: 16-byte nonce and separate 16-byte tag", async () => {
    const key = await keyFromHex(fixtures.cases[0].keyHex);
    const envelope = JSON.parse(await encrypt(key, "hi"));
    expect(Object.keys(envelope).sort()).toEqual(["ciphertext", "nonce", "tag"]);
    expect(base64ToBytes(envelope.nonce)).toHaveLength(16);
    expect(base64ToBytes(envelope.tag)).toHaveLength(16);
    expect(base64ToBytes(envelope.ciphertext)).toHaveLength(2);
  });

  it("round-trips", async () => {
    const key = await keyFromHex(fixtures.cases[1].keyHex);
    const text = "round trip ✓ " + "x".repeat(100_000);
    expect(await decrypt(key, await encrypt(key, text))).toBe(text);
  });

  // Needs python3 with pycryptodome; skipped otherwise.
  const python = spawnSync("python3", ["-c", "import Crypto"]).status === 0;
  it.skipIf(!python)("is decrypted by the desktop client's CipherManager", async () => {
    const c = fixtures.cases[1];
    const plaintext = "from the extension 🚀";
    const payload = await encrypt(await keyFromHex(c.keyHex), plaintext);
    const desktopSrc = fileURLToPath(new URL("../../ClipCascade_Desktop/src", import.meta.url));
    const script = `
import sys, json
sys.path.insert(0, ${JSON.stringify(desktopSrc)})
from types import SimpleNamespace
from utils.cipher_manager import CipherManager
config = SimpleNamespace(data={"hashed_password": bytes.fromhex(${JSON.stringify(c.keyHex)})})
payload = sys.stdin.read()
sys.stdout.write(CipherManager(config).decrypt(**CipherManager.decode_from_json_string(payload)))
`;
    const result = spawnSync("python3", ["-c", script], { input: payload, encoding: "utf8" });
    expect(result.stderr).toBe("");
    expect(result.stdout).toBe(plaintext);
  });
});
